version: '3.8'

services:
  university-startups:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LYZR_API_KEY=${LYZR_API_KEY}
      - LYZR_API_BASE_URL=${LYZR_API_BASE_URL:-https://api.lyzr.ai}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  university-startups-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - LYZR_API_KEY=${LYZR_API_KEY}
      - LYZR_API_BASE_URL=${LYZR_API_BASE_URL:-https://api.lyzr.ai}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    profiles:
      - dev

